### PR TITLE
#38 update go version + libs + fix errors and deprecation warnings

### LINKED ISSUE #38: Update K8s-Libs & RBAC-Proxy, fix resulting errors and deprecation warnings

### PR DESCRIPTION
**Pull request by jelemux**
Resolves #38

### CODE REVIEW

File: main_test.go [hunk 1]
```diff
@@ -78,7 +58,11 @@ func Test_startManager(t *testing.T) {
 		// given
 		err := os.Unsetenv("WATCH_NAMESPACE")
 		require.NoError(t, err)
-		getNewMockManager(t, nil, nil)
+		k8sManager := newMockK8sManager(t)
+		ctrl.NewManager = func(config *rest.Config, options manager.Options) (manager.Manager, error) {
```
Comment (nhinze23) [inline main_test.go:62]: Save NewManager method and reset it with defer

File: main_test.go [hunk 2]
```diff
@@ -90,118 +74,137 @@ func Test_startManager(t *testing.T) {
 
 	t.Setenv(namespaceEnvVar, "mynamespace")
 
-	expectedError := fmt.Errorf("this is my expected error")
-
 	t.Run("Test with error on manager creation", func(t *testing.T) {
 		// given
-		getNewMockManager(t, expectedError, nil)
+		ctrl.NewManager = func(config *rest.Config, options manager.Options) (manager.Manager, error) {
```
Comment (nhinze23) [inline main_test.go:79]: Save NewManager method and reset it with defer

File: main_test.go [hunk 3]
```diff
@@ -90,118 +74,137 @@ func Test_startManager(t *testing.T) {
...
 		// given
-		mockDefinitions := map[string]mockDefinition{
-			"GetClient":           {ReturnValue: client},
-			"Add":                 {Arguments: []interface{}{mock.Anything}, ReturnValue: expectedError},
-			"GetEventRecorderFor": {Arguments: []interface{}{"k8s-service-discovery-controller-manager"}, ReturnValue: nil},
+		k8sManager := newMockK8sManager(t)
+		k8sManager.EXPECT().GetClient().Return(client)
+		k8sManager.EXPECT().Add(mock.Anything).Return(assert.AnError)
+		k8sManager.EXPECT().GetEventRecorderFor("k8s-service-discovery-controller-manager").Return(nil)
+		ctrl.NewManager = func(config *rest.Config, options manager.Options) (manager.Manager, error) {
```
Comment (nhinze23) [inline main_test.go:98]: Save NewManager method and reset it with defer

File: main_test.go [hunk 4]
```diff
@@ -90,118 +74,137 @@ func Test_startManager(t *testing.T) {
...
+		k8sManager := newMockK8sManager(t)
+		k8sManager.EXPECT().GetClient().Return(client)
+		k8sManager.EXPECT().Add(mock.Anything).Return(nil)
+		k8sManager.EXPECT().GetEventRecorderFor("k8s-service-discovery-controller-manager").Return(nil)
+		k8sManager.EXPECT().GetControllerOptions().Return(config.Controller{})
+		k8sManager.EXPECT().GetScheme().Return(scheme)
+		k8sManager.EXPECT().GetLogger().Return(logger)
+		k8sManager.EXPECT().GetCache().Return(nil)
+		k8sManager.EXPECT().AddHealthzCheck(mock.Anything, mock.Anything).Return(assert.AnError)
+		ctrl.NewManager = func(config *rest.Config, options manager.Options) (manager.Manager, error) {
```
Comment (nhinze23) [inline main_test.go:122]: Save NewManager method and reset it with defer

File: main_test.go [hunk 5]
```diff
@@ -90,118 +74,137 @@ func Test_startManager(t *testing.T) {
...
+		k8sManager.EXPECT().Add(mock.Anything).Return(nil)
+		k8sManager.EXPECT().GetEventRecorderFor("k8s-service-discovery-controller-manager").Return(nil)
+		k8sManager.EXPECT().GetControllerOptions().Return(config.Controller{})
+		k8sManager.EXPECT().GetScheme().Return(scheme)
+		k8sManager.EXPECT().GetLogger().Return(logger)
+		k8sManager.EXPECT().GetCache().Return(nil)
+		k8sManager.EXPECT().AddHealthzCheck(mock.Anything, mock.Anything).Return(nil)
+		k8sManager.EXPECT().AddReadyzCheck(mock.Anything, mock.Anything).Return(nil)
+		k8sManager.EXPECT().Start(mock.Anything).Return(nil)
+		ctrl.NewManager = func(config *rest.Config, options manager.Options) (manager.Manager, error) {
```
Comment (nhinze23) [inline main_test.go:199]: Save NewManager method and reset it with defer

File: main_test.go [hunk 6]
```diff
@@ -90,118 +74,137 @@ func Test_startManager(t *testing.T) {
...
+		k8sManager.EXPECT().Add(mock.Anything).Return(nil)
+		k8sManager.EXPECT().GetEventRecorderFor("k8s-service-discovery-controller-manager").Return(nil)
+		k8sManager.EXPECT().GetControllerOptions().Return(config.Controller{})
+		k8sManager.EXPECT().GetScheme().Return(scheme)
+		k8sManager.EXPECT().GetLogger().Return(logger)
+		k8sManager.EXPECT().GetCache().Return(nil)
+		k8sManager.EXPECT().AddHealthzCheck(mock.Anything, mock.Anything).Return(nil)
+		k8sManager.EXPECT().AddReadyzCheck(mock.Anything, mock.Anything).Return(nil)
+		k8sManager.EXPECT().Start(mock.Anything).Return(assert.AnError)
+		ctrl.NewManager = func(config *rest.Config, options manager.Options) (manager.Manager, error) {
```
Comment (nhinze23) [inline main_test.go:173]: Save NewManager method and reset it with defer

File: main_test.go [hunk 7]
```diff
@@ -90,118 +74,137 @@ func Test_startManager(t *testing.T) {
...
+		k8sManager.EXPECT().GetClient().Return(client)
+		k8sManager.EXPECT().Add(mock.Anything).Return(nil)
+		k8sManager.EXPECT().GetEventRecorderFor("k8s-service-discovery-controller-manager").Return(nil)
+		k8sManager.EXPECT().GetControllerOptions().Return(config.Controller{})
+		k8sManager.EXPECT().GetScheme().Return(scheme)
+		k8sManager.EXPECT().GetLogger().Return(logger)
+		k8sManager.EXPECT().GetCache().Return(nil)
+		k8sManager.EXPECT().AddHealthzCheck(mock.Anything, mock.Anything).Return(nil)
+		k8sManager.EXPECT().AddReadyzCheck(mock.Anything, mock.Anything).Return(assert.AnError)
+		ctrl.NewManager = func(config *rest.Config, options manager.Options) (manager.Manager, error) {
```
Comment (nhinze23) [inline main_test.go:147]: Save NewManager method and reset it with defer

**Comment by nhinze23** [comment]
lgtm
